/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufv.caf.erp;

import br.ufv.caf.erp.model.entity.Address;
import br.ufv.caf.erp.model.entity.Customer;
import br.ufv.caf.erp.model.entity.Product;
import br.ufv.caf.erp.model.entity.ProductSold;
import br.ufv.caf.erp.model.entity.Sale;
import br.ufv.caf.erp.model.enums.SaleStatus;
import br.ufv.caf.erp.controller.ControllerCustomer;
import br.ufv.caf.erp.controller.ControllerProduct;
import br.ufv.caf.erp.controller.ControllerSales;
import br.ufv.caf.erp.register.RegisterCustomer;
import br.ufv.caf.erp.register.RegisterCustomerAddress;
import br.ufv.caf.erp.register.RegisterProduct;
import br.ufv.caf.erp.register.RegisterSale;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author aslan
 */
public class Interface extends javax.swing.JFrame {
    
    ControllerProduct ControllerProduct;
    ControllerCustomer ControllerCustomer;
    ControllerSales ControllerSales;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        //ImageIcon icon = new ImageIcon("./et.jpg");
        this.ControllerProduct=new ControllerProduct();
        this.ControllerCustomer=new ControllerCustomer();
        this.ControllerSales=new ControllerSales();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBoxProducts = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldProductCode = new javax.swing.JTextField();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldProductQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldProductCategory = new javax.swing.JTextField();
        jTextFieldProductPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldProductDescription = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jTextFieldSearchProduct = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jTextFieldCustomerCode = new javax.swing.JTextField();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jToggleButton4 = new javax.swing.JToggleButton();
        jTextFieldCustomerCPF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBoxCustomers = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCustomerEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCustomerPassword = new javax.swing.JTextField();
        jComboBoxCustomerAddress = new javax.swing.JComboBox<>();
        jToggleButton6 = new javax.swing.JToggleButton();
        jTextFieldSearchCustomer = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBoxSales = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldSaleCustomer = new javax.swing.JTextField();
        jComboBoxSaleProducts = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxSaleStatus = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldSaleAddress = new javax.swing.JTextField();
        jTextFieldSaleSearchDay = new javax.swing.JTextField();
        jTextFieldSaleSearchMonthy = new javax.swing.JTextField();
        jTextFieldSaleSearchYear = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("Bem vindo ao sistema de produtos");

        jLabel22.setText("Feito por:");

        jLabel23.setText("Leandro L. A. Vieira");

        jLabel24.setText("jLabel24");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(104, 104, 104))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel20)
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(28, 28, 28)
                .addComponent(jLabel24)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel4);

        jButton1.setText("Adicionar Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductsActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Preço:");

        jLabel6.setText("Descrição:");

        jTextFieldProductCode.setEditable(false);
        jTextFieldProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductCodeActionPerformed(evt);
            }
        });

        jTextFieldProductName.setEditable(false);
        jTextFieldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductNameActionPerformed(evt);
            }
        });

        jLabel8.setText("Categoria:");

        jTextFieldProductCategory.setEditable(false);

        jTextFieldProductPrice.setEditable(false);

        jTextFieldProductDescription.setEditable(false);
        jTextFieldProductDescription.setColumns(20);
        jTextFieldProductDescription.setRows(5);
        jScrollPane1.setViewportView(jTextFieldProductDescription);

        jToggleButton1.setText("Editar quantidade");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Deletar produto");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxProducts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldProductCode)
                    .addComponent(jTextFieldProductName)
                    .addComponent(jTextFieldProductCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldProductQuantity)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jTextFieldSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanel1);

        jLabel7.setText("CPF:");

        jLabel9.setText("Senha:");

        jLabel10.setText("Endereços:");

        jToggleButton3.setText("Editar dados do cliente");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jTextFieldCustomerCode.setEditable(false);
        jTextFieldCustomerCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerCodeActionPerformed(evt);
            }
        });

        jTextFieldCustomerName.setEditable(false);
        jTextFieldCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerNameActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Deletar cliente");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Email:");

        jButton2.setText("Adicionar cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCustomersActionPerformed(evt);
            }
        });

        jLabel13.setText("Código:");

        jTextFieldCustomerEmail.setEditable(false);

        jLabel14.setText("Nome:");

        jTextFieldCustomerPassword.setEditable(false);

        jToggleButton6.setText("Adicionar endereço");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jTextFieldSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCustomerActionPerformed(evt);
            }
        });

        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCustomerCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCustomerCode)
                    .addComponent(jTextFieldCustomerName)
                    .addComponent(jTextFieldCustomerEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCustomerPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jToggleButton3))
                    .addComponent(jComboBoxCustomerAddress, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearchCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextFieldSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(20, 20, 20)
                .addComponent(jComboBoxCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCustomerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCustomerCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCustomerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton3))
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jButton3.setText("Adicionar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBoxSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalesActionPerformed(evt);
            }
        });

        jLabel16.setText("Cliente:");

        jLabel17.setText("Produtos:");

        jLabel18.setText("Status:");

        jComboBoxSaleStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "inProgress", "delivered" }));

        jButton4.setText("Editar Status");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel19.setText("Endereço:");

        jTextFieldSaleAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaleAddressActionPerformed(evt);
            }
        });

        jButton7.setText("Pesquisar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Dia");

        jLabel12.setText("Mês");

        jLabel15.setText("Ano");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxSales, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSaleCustomer, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSaleProducts, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSaleStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSaleAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSaleSearchDay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSaleSearchMonthy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldSaleSearchYear, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextFieldSaleSearchDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSaleSearchMonthy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSaleSearchYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaleCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaleAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSaleProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSaleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jComboBoxProducts.getItemCount()>0){
            this.jComboBoxProducts.setSelectedItem(null);
        }
        this.jComboBoxProducts.removeAllItems();
        RegisterProduct registerProduct=new RegisterProduct(this.ControllerProduct);
        registerProduct.setVisible(true);
        registerProduct.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        registerProduct.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                unfreezeThisJFrame();
                updateJListProducts();
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductsActionPerformed
        Product selectedProduct=(Product)this.jComboBoxProducts.getSelectedItem();
        if(this.jComboBoxProducts.getSelectedItem()!=null){
            this.jTextFieldProductCode.setText(Integer.toString(selectedProduct.getCode()));
            this.jTextFieldProductName.setText(selectedProduct.getName());
            this.jTextFieldProductQuantity.setText(Integer.toString(selectedProduct.getQuantity()));
            this.jTextFieldProductCategory.setText(selectedProduct.getCategory());
            this.jTextFieldProductPrice.setText(Double.toString(selectedProduct.getPrice()));
            this.jTextFieldProductDescription.setText(selectedProduct.getDescription());
        }else{
            this.jTextFieldProductCode.setText("");
            this.jTextFieldProductName.setText("");
            this.jTextFieldProductQuantity.setText("");
            this.jTextFieldProductCategory.setText("");
            this.jTextFieldProductPrice.setText("");
            this.jTextFieldProductDescription.setText("");
        }
        //System.out.println(selectedProduct);
    }//GEN-LAST:event_jComboBoxProductsActionPerformed

    private void jTextFieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameActionPerformed

    private void jTextFieldProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductCodeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.ControllerProduct.setQuantity(Integer.parseInt(this.jTextFieldProductCode.getText()), Integer.parseInt(this.jTextFieldProductQuantity.getText()));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextFieldCustomerCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerCodeActionPerformed

    private void jTextFieldCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.jComboBoxCustomers.getItemCount()>0){
            this.jComboBoxCustomers.setSelectedItem(null);
        }
        this.jComboBoxCustomers.removeAllItems();
        RegisterCustomer registerCustomer=new RegisterCustomer(this.ControllerCustomer);
        registerCustomer.setVisible(true);
        registerCustomer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        registerCustomer.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                unfreezeThisJFrame();
                updateJListCustomers();
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCustomersActionPerformed
        this.jComboBoxCustomerAddress.removeAllItems();
        if(this.jComboBoxCustomers.getSelectedItem()!=null){
            Customer selectedCustomer=(Customer)this.jComboBoxCustomers.getSelectedItem();
            this.jTextFieldCustomerCode.setText(Integer.toString(selectedCustomer.getCode()));
            this.jTextFieldCustomerName.setText(selectedCustomer.getName());
            this.jTextFieldCustomerCPF.setText(selectedCustomer.getCPF());
            this.jTextFieldCustomerEmail.setText(selectedCustomer.getEmail());
            this.jTextFieldCustomerPassword.setText(selectedCustomer.getPassword());
            
            for(Address address: selectedCustomer.getAllAddress()){
                System.out.println(address);
                this.jComboBoxCustomerAddress.addItem(address);
            }
        }else{
            this.jTextFieldCustomerCode.setText("");
            this.jTextFieldCustomerName.setText("");
            this.jTextFieldCustomerCPF.setText("");
            this.jTextFieldCustomerEmail.setText("");
            this.jTextFieldCustomerPassword.setText("");          
            this.jComboBoxCustomerAddress.removeAllItems();
        }
    }//GEN-LAST:event_jComboBoxCustomersActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        if(this.jComboBoxCustomerAddress.getItemCount()>0){
            this.jComboBoxCustomerAddress.setSelectedItem(null);
        }
        this.jComboBoxCustomerAddress.removeAllItems();
        RegisterCustomerAddress registerCustomerAdsress=new RegisterCustomerAddress(this.ControllerCustomer, ((Customer)this.jComboBoxCustomers.getSelectedItem()).getCode());
        registerCustomerAdsress.setVisible(true);
        registerCustomerAdsress.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        registerCustomerAdsress.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                unfreezeThisJFrame();
                updateJListCustomerAddress();
            }
        });
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(this.jComboBoxSales.getItemCount()>0){
            this.jComboBoxSales.setSelectedItem(null);
        }
        this.jComboBoxSales.removeAllItems();
        RegisterSale registerSale=new RegisterSale(this.ControllerProduct, this.ControllerCustomer, this.ControllerSales);
        registerSale.setVisible(true);
        registerSale.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        registerSale.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                unfreezeThisJFrame();
                updateJListSales();
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldSaleAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaleAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaleAddressActionPerformed

    private void jComboBoxSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSalesActionPerformed
        Sale sale=(Sale)this.jComboBoxSales.getSelectedItem();
        if(sale!=null){            
            this.jTextFieldSaleCustomer.setText(this.ControllerCustomer.search(sale.getClientCode()).getName());
            this.jTextFieldSaleAddress.setText(this.ControllerCustomer.searchAddress(sale.getClientCode(), sale.getAddressCode()).toString());
            
            this.jComboBoxSaleProducts.removeAllItems();
            for(ProductSold productSold:sale.getProducts()){
                this.jComboBoxSaleProducts.addItem(this.ControllerProduct.search(productSold.getProductCode()));
            }
                    
            SaleStatus saleStatus=sale.getSaleStatus();
            if(saleStatus==SaleStatus.pending){
                this.jComboBoxSaleStatus.setSelectedIndex(0);
            }else if(saleStatus==SaleStatus.inProgress){
                this.jComboBoxSaleStatus.setSelectedIndex(1);
            }else{
                this.jComboBoxSaleStatus.setSelectedIndex(2);
            }
            
        }else{
            this.jTextFieldSaleCustomer.setText("");
            this.jTextFieldSaleAddress.setText("");
            this.jComboBoxSaleProducts.removeAllItems();
            this.jComboBoxSaleStatus.setSelectedIndex(0);                
        }
    }//GEN-LAST:event_jComboBoxSalesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Sale sale=(Sale)this.jComboBoxSales.getSelectedItem();
        int selectedStatusIndex=this.jComboBoxSaleStatus.getSelectedIndex();
        if(sale!=null){
            if(selectedStatusIndex==0){
                this.ControllerSales.setSaleStatus(sale.getCode(), SaleStatus.pending);
            }else if(selectedStatusIndex==1){
                this.ControllerSales.setSaleStatus(sale.getCode(), SaleStatus.inProgress);
            }else{
                this.ControllerSales.setSaleStatus(sale.getCode(), SaleStatus.delivered);
            }
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.jComboBoxProducts.getItemCount()>0){
            this.jComboBoxProducts.setSelectedItem(null);
        }
        this.jComboBoxProducts.removeAllItems();
        this.updateJListProducts();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCustomerActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.jComboBoxCustomers.getItemCount()>0){
            this.jComboBoxCustomers.setSelectedItem(null);
        }
        this.jComboBoxCustomers.removeAllItems();
        this.updateJListCustomers();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(this.jComboBoxSales.getItemCount()>0){
            this.jComboBoxSales.setSelectedItem(null);
        }
        this.jComboBoxSales.removeAllItems();
        this.updateJListSalesByDate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if(this.jComboBoxCustomers.getSelectedItem()!=null){
            this.ControllerCustomer.setActive(((Customer)this.jComboBoxCustomers.getSelectedItem()).getCode(), false);
        }
        
        if(this.jComboBoxCustomers.getItemCount()>0){
            this.jComboBoxCustomers.setSelectedItem(null);
        }
        
        this.jComboBoxCustomers.removeAllItems();
        this.updateJListCustomers();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if(this.jComboBoxProducts.getSelectedItem()!=null){
            this.ControllerProduct.setSalable(((Product)this.jComboBoxProducts.getSelectedItem()).getCode(), false);
        }
        
        if(this.jComboBoxProducts.getItemCount()>0){
            this.jComboBoxProducts.setSelectedItem(null);
        }
        
        this.jComboBoxProducts.removeAllItems();
        this.updateJListProducts();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    public void unfreezeThisJFrame(){
        this.setEnabled(true);
    }
    
    public void updateJListProducts(){
        //this.jComboBoxProducts.setModel(new DefaultComboBoxModel<>(this.ControllerProduct.getAllProducts().toArray()));
        for(Product product: this.ControllerProduct.searchByName(this.jTextFieldSearchProduct.getText())){
            System.out.println(product);
            this.jComboBoxProducts.addItem(product);
        }
    }
    
    public void updateJListCustomers(){
        //this.jComboBoxProducts.setModel(new DefaultComboBoxModel<>(this.ControllerProduct.getAllProducts().toArray()));
        for(Customer customer: this.ControllerCustomer.searchByName(this.jTextFieldSearchCustomer.getText())){
            System.out.println("Mostre"+customer.isActive());
            this.jComboBoxCustomers.addItem(customer);
        }
    }
    
    public void updateJListCustomerAddress(){
        //this.jComboBoxProducts.setModel(new DefaultComboBoxModel<>(this.ControllerProduct.getAllProducts().toArray()));
        for(Address address: ((Customer)this.jComboBoxCustomers.getSelectedItem()).getAllAddress()){
            System.out.println(address);
            this.jComboBoxCustomerAddress.addItem(address);
        }
    }
    
    public void updateJListSalesByDate(){
        LocalDate date = LocalDate.of(Integer.parseInt(this.jTextFieldSaleSearchYear.getText()), Integer.parseInt(this.jTextFieldSaleSearchMonthy.getText()), Integer.parseInt(this.jTextFieldSaleSearchDay.getText()));
        //this.jComboBoxProducts.setModel(new DefaultComboBoxModel<>(this.ControllerProduct.getAllProducts().toArray()));
        for(Sale sale: this.ControllerSales.searchByDate(date)){
            System.out.println(sale);
            this.jComboBoxSales.addItem(sale);
        }
    }
    
    public void updateJListSales(){
        //this.jComboBoxProducts.setModel(new DefaultComboBoxModel<>(this.ControllerProduct.getAllProducts().toArray()));
        for(Sale sale: this.ControllerSales.getAllSales()){
            System.out.println(sale);
            this.jComboBoxSales.addItem(sale);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<Object> jComboBoxCustomerAddress;
    private javax.swing.JComboBox<Object> jComboBoxCustomers;
    private javax.swing.JComboBox<Object> jComboBoxProducts;
    private javax.swing.JComboBox<Object> jComboBoxSaleProducts;
    private javax.swing.JComboBox<String> jComboBoxSaleStatus;
    private javax.swing.JComboBox<Object> jComboBoxSales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCustomerCPF;
    private javax.swing.JTextField jTextFieldCustomerCode;
    private javax.swing.JTextField jTextFieldCustomerEmail;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldCustomerPassword;
    private javax.swing.JTextField jTextFieldProductCategory;
    private javax.swing.JTextField jTextFieldProductCode;
    private javax.swing.JTextArea jTextFieldProductDescription;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldProductPrice;
    private javax.swing.JTextField jTextFieldProductQuantity;
    private javax.swing.JTextField jTextFieldSaleAddress;
    private javax.swing.JTextField jTextFieldSaleCustomer;
    private javax.swing.JTextField jTextFieldSaleSearchDay;
    private javax.swing.JTextField jTextFieldSaleSearchMonthy;
    private javax.swing.JTextField jTextFieldSaleSearchYear;
    private javax.swing.JTextField jTextFieldSearchCustomer;
    private javax.swing.JTextField jTextFieldSearchProduct;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
